In [24]:
import pandas as pd
import matplotlib.pyplot as plt

In [25]:
fts = pd.read_csv('fine_tuned_scores.csv')
fts.head()

,task,standard model score,fine tuned score,reasoning,self_reflection,answer,model,finetuned_model
0,What is the longest river in the world?,NaN,9.0,The Nile River is often cited as the longest r...,I will include that some experts argue about t...,"Traditionally, the Nile River is considered th...",The Nile River is often cited as the longest ...,The longest river in the world is the Nile Ri...
1,How do vaccines work?,NaN,8.0,Vaccines work by stimulating the immune system...,I need to ensure that the mechanism of buildin...,Vaccines introduce a harmless component of a p...,\nVaccines are made from inactivated or weake...,Vaccines protect our bodies by introducing a ...
2,What is gravity?,NaN,8.0,Gravity is the force that pulls objects toward...,Correct. I could also mention it was formulate...,Gravity is the force that attracts objects tow...,Gravity is a fundamental force of nature that...,Gravity is a fundamental force of nature that...
3,What is the significance of the Sistine Chapel...,NaN,9.0,"The Sistine Chapel ceiling, painted by Michela...",Referencing both the artist and the subject ma...,The Sistine Chapel ceiling is significant for ...,Michelangelo's work on the ceiling is widely ...,Michelangelo's frescoes are renowned for thei...
4,What is the difference between weather and cli...,NaN,9.0,Weather refers to the short-term atmospheric c...,"The distinction is correct, but I should empha...",Weather is the short-term atmospheric conditio...,Weather refers to short-term atmospheric cond...,Weather refers to the short-term atmospheric ...

In [26]:
ms = pd.read_csv('data/scores_llama70b.csv')
ms.head()

,task,reasoning,self_reflection,answer,model,finetuned_model,standard_model_score,finetuned_model_score
0,What is the longest river in the world?,The Nile River is often cited as the longest r...,I will include that some experts argue about t...,"Traditionally, the Nile River is considered th...",The Nile River is often considered the longes...,The Nile River is the longest river in the wo...,8,9
1,How do vaccines work?,Vaccines work by stimulating the immune system...,I need to ensure that the mechanism of buildin...,Vaccines introduce a harmless component of a p...,Vaccines contain weakened or inactivated path...,Vaccines are a safe and effective way to prev...,8,6
2,What is gravity?,Gravity is the force that pulls objects toward...,Correct. I could also mention it was formulate...,Gravity is the force that attracts objects tow...,Gravity is a fundamental force of nature that...,Gravity is a fundamental force of nature that...,8,7
3,What is the significance of the Sistine Chapel...,"The Sistine Chapel ceiling, painted by Michela...",Referencing both the artist and the subject ma...,The Sistine Chapel ceiling is significant for ...,Michelangelo's masterpiece\nThe Sistine Chape...,Michelangelo's frescoes depict the Last Judgm...,8,7
4,What is the difference between weather and cli...,Weather refers to the short-term atmospheric c...,"The distinction is correct, but I should empha...",Weather is the short-term atmospheric conditio...,Weather refers to the temporary and local con...,Weather refers to short-term atmospheric cond...,9,8

In [31]:
llama_stan = ms['standard_model_score'].sum() / ms.shape[0]

In [32]:
llama_fin = ms['finetuned_model_score'].sum() / ms.shape[0]

In [4]:
(ms['task'] == fts['task']).count()

np.int64(105)

In [5]:
ms['finetuned_model_score'] = fts['fine tuned score']

In [6]:
ms

,task,reasoning,self_reflection,answer,model,finetuned_model,standard_model_score,finetuned_model_score
0,What is the longest river in the world?,The Nile River is often cited as the longest r...,I will include that some experts argue about t...,"Traditionally, the Nile River is considered th...",The Nile River is often considered the longes...,The Nile River is the longest river in the wo...,8,9.0
1,How do vaccines work?,Vaccines work by stimulating the immune system...,I need to ensure that the mechanism of buildin...,Vaccines introduce a harmless component of a p...,Vaccines contain weakened or inactivated path...,Vaccines are a safe and effective way to prev...,8,8.0
2,What is gravity?,Gravity is the force that pulls objects toward...,Correct. I could also mention it was formulate...,Gravity is the force that attracts objects tow...,Gravity is a fundamental force of nature that...,Gravity is a fundamental force of nature that...,8,8.0
3,What is the significance of the Sistine Chapel...,"The Sistine Chapel ceiling, painted by Michela...",Referencing both the artist and the subject ma...,The Sistine Chapel ceiling is significant for ...,Michelangelo's masterpiece\nThe Sistine Chape...,Michelangelo's frescoes depict the Last Judgm...,8,9.0
4,What is the difference between weather and cli...,Weather refers to the short-term atmospheric c...,"The distinction is correct, but I should empha...",Weather is the short-term atmospheric conditio...,Weather refers to the temporary and local con...,Weather refers to short-term atmospheric cond...,9,9.0
...,...,...,...,...,...,...,...,...
100,What is the boiling point of water in Celsius?,The boiling point of water is 100 degrees Cels...,100 degrees Celsius is correct for the boiling...,The boiling point of water is 100 degrees Cels...,100°C\nThe boiling point of water is 100°C. \...,100°C. Water boils at 100°C at standard atmos...,8,2.0
101,What is a virus?,A virus is a non-living infectious agent that ...,Clarify it’s acellular and differs from bacteria.,A virus is an acellular infectious agent that ...,A virus is a small infectious agent that repl...,A virus is a small infectious agent that repl...,9,7.0
102,What is the function of chlorophyll in plants?,Chlorophyll is the pigment responsible for abs...,I need to emphasize its crucial role in captur...,"Chlorophyll absorbs sunlight, which is then us...",Chlorophyll is a green pigment found in the c...,Chlorophyll is the green pigment found in pla...,9,6.4
103,What is the difference between a concave and c...,A concave lens is thinner in the middle and di...,I should clarify that concave lenses are used ...,"A concave lens, used in glasses for nearsighte...","In terms of focal length, what is the differe...",A concave lens is thicker in the middle than ...,2,1.8
104,What is the boiling point of water in Celsius?,"Under standard atmospheric pressure, water boi...",I confirmed that no additional context is need...,Water boils at 100 degrees Celsius under stand...,\nThe boiling point of water is 100 degrees C...,100°C.\nThe boiling point of water is 100°C. ...,8,8.8

In [33]:
ms.to_csv('data/scores_o3-mini.csv', index=False)

In [8]:
import plotly.express as px

In [9]:
fig = px.line(ms, x="finetuned_model_score", y="standard_model_score", title='Life expectancy in Canada')
fig.show()

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

In [15]:
ms.shape

(105, 8)

In [22]:
ms['finetuned_model_score'].mean()

np.float64(8.082692307692307)

In [23]:
ms['standard_model_score'].mean()

np.float64(7.580952380952381)

In [34]:
percentage_increase = str(round((841 - 796)/796 * 100, 2)) + '%'
percentage_increase

'5.65%'